package com.anshul;

import java.io.IOException;

import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.google.appengine.api.datastore.DatastoreService;
import com.google.appengine.api.datastore.DatastoreServiceFactory;
import com.google.appengine.api.datastore.Entity;

@SuppressWarnings("serial")
public class PopulateRadio extends HttpServlet {
	@Override
	  public void doGet(HttpServletRequest req, HttpServletResponse resp)
	      throws IOException {
		DatastoreService datastore = DatastoreServiceFactory.getDatastoreService();
	    
		Entity station = new Entity("Station");
		station.setProperty("name", "100 HIT radio");
		station.setProperty("description", "UK, US and Euro Charts top 100 music, 24/7.");
		station.setProperty("url", "http://listen.radionomy.com/100-HIT-radio");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/20110307013002-logo3.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/100-HIT-radio.m3u");
		station.setProperty("tag", 	"Hits TopCharts Pop RnB Dance");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "BestRadio");
		station.setProperty("description", "Best hits, 24/7! The best hits, 24/7!");
		station.setProperty("url", "http://listen.radionomy.com/bestradio");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/5f073f544d0b42b6a7683be0c09bc5f0_635113880521354373.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/bestradio.m3u");
		station.setProperty("tag", 	"Hits HitsUSA Oldies Dance");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "#1 Hits");
		station.setProperty("description", "Using downloads, shares and radio play #1 Hits has compiled the biggest songs in the World all in one place. Powered by NowTrending.com and a proud partner of the Radio League. Get unlimited, free music by downloading the Radio League app in the App Store or Marketplace Now!");
		station.setProperty("url", "http://listen.radionomy.com/-1hits");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/6382c82efc7f46d3b8edf679f653ba4f_635328409068147786.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/-1hits.m3u");
		station.setProperty("tag", 	"Hits HitsUSA TopCharts");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "ABCD Hits");
		station.setProperty("description", "Best Hits Music !");
		station.setProperty("url", "http://listen.radionomy.com/abcd-hits");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/0a292db95cef4ea793b18816df870f4d_635114046528666828.72x72.png");
		station.setProperty("m3u", "http://listen.radionomy.com/abcd-hits.m3u");
		station.setProperty("tag", 	"Hits TopCharts Pop RnB Dance");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "Fiive-Radio");
		station.setProperty("description", "100% Dancefloor! Good listening!");
		station.setProperty("url", "http://listen.radionomy.com/fiive-radio");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/201208051411571883.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/fiive-radio.m3u");
		station.setProperty("tag", 	"Hits TopCharts RnB Dance");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "FeeverMix");
		station.setProperty("description", "MixFeever is the 100% Club radio broadcast 24H/24!");
		station.setProperty("url", "http://listen.radionomy.com/feevermix");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/3bcdd76a92774a84bbfb0c462a92be88_635007603642429645.72x72.png");
		station.setProperty("m3u", "http://listen.radionomy.com/feevermix.m3u");
		station.setProperty("tag", 	"Electronic Trance House Electro Dance");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "Happyness");
		station.setProperty("description", "Happyness Radio - Songs to listen when you are happy");
		station.setProperty("url", "http://listen.radionomy.com/happyness");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/3d8fd4cad3c04dea926ed15ab2b055ef_635327625950642913.72x72.png");
		station.setProperty("m3u", "http://listen.radionomy.com/happyness.m3u");
		station.setProperty("tag", 	"Electronic Hits House Rap Dance");
		station.setProperty("mood", "happiness");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "AMBIENT AND LOUNGE");
		station.setProperty("description", "Sexy House Music ");
		station.setProperty("url", "http://listen.radionomy.com/ambient-and-lounge");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/201203131611431401.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/ambient-and-lounge.m3u");
		station.setProperty("tag", 	"House Dance");
		station.setProperty("mood", "fear");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "Ibiza Party Radio");
		station.setProperty("description", "The Ibiza Way of Fun");
		station.setProperty("url", "http://listen.radionomy.com/ibiza-party-radio");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/20111217211734-IBIZA_PARTY_RADIO.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/ibiza-party-radio.m3u");
		station.setProperty("tag", 	"House Dance Lounge Techno Chill-out");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "One love Hip Hop Radio");
		station.setProperty("description", "Classic and New Hip Hop and R&B");
		station.setProperty("url", "http://listen.radionomy.com/one-love-hip-hop-radio");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/775ff6083622435da3d3224307d0ec58_635114984716483412.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/one-love-hip-hop-radio.m3u");
		station.setProperty("tag", 	"Hip-hop Dancehall Rap RnB Urban");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "CurveRadio");
		station.setProperty("description", "Feel The Curve Beats");
		station.setProperty("url", "http://listen.radionomy.com/curveradio");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/46b6f68ceaf748029bca5d2536fd0e66_635235743144673050.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/curveradio.m3u");
		station.setProperty("tag", 	"Dubstep Electro House Techno Reggaeton");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "Musicalia");
		station.setProperty("description", "Musicalia Radio is a radio station from the Valley of Almanzora. We you can hear through the 96.8 FM or on our website ");
		station.setProperty("url", "http://listen.radionomy.com/musicalia");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/4a491a749d2444df9b54ea8164bd4afd_635317007815446779.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/musicalia.m3u");
		station.setProperty("tag", 	"Hip-hop Dancehall Rap RnB Urban");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "Bollywood N Bhangra USA");
		station.setProperty("description", "Bollywood is awesome. Bhangra is too.");
		station.setProperty("url", "http://listen.radionomy.com/bollywood-n-bhangra-usa");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/201206300150046931.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/bollywood-n-bhangra-usa.m3u");
		station.setProperty("tag", 	"Asian Bollywood Dance");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "Ambiance Lounge");
		station.setProperty("description", "Soft and lounge music");
		station.setProperty("url", "http://listen.radionomy.com/ambiance-lounge");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/605a9db619f14c148e6dbb72758800c2_635115094180501020.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/ambiance-lounge.m3u");
		station.setProperty("tag", 	"Lounge Ambient Chill-out Downtempo");
		station.setProperty("mood", "anger");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "ANGERADIO");
		station.setProperty("description", "RADIO ALL TUBES");
		station.setProperty("url", "http://listen.radionomy.com/angeradio");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/10a9ecfc4f68499eb7be616881c09c85_635297016242602214.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/angeradio.m3u");
		station.setProperty("tag", 	"Blues Country ClassicRock Folk Folkloric");
		station.setProperty("mood", "anger");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "Thrash Zone Radio");
		station.setProperty("description", "Thrash Zone Radio, the only radio station dedicated to Metal faster and brutal styles, Thrash! Kreator, Sodom, Exodus, Overkill .. Here, no mainstream shit! From classics to new releases, through the beads a little less known is that your neck will morfler!");
		station.setProperty("url", "http://listen.radionomy.com/thrash-zone-radio");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/201208101332374904.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/thrash-zone-radio.m3u");
		station.setProperty("tag", 	"DeathMetal HeavyMetal Metal TrashMetal");
		station.setProperty("mood", "disgust");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "100 CHILL");
		station.setProperty("description", "100% Lounge and Chill-out music.");
		station.setProperty("url", "http://listen.radionomy.com/100-chill");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/20110726134411-logo.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/100-chill.m3u");
		station.setProperty("tag", 	"Chill-out EasyListening Lounge Jazz Ambient");
		station.setProperty("mood", "sadness");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "SMOOTH RIVIERA");
		station.setProperty("description", "Meditation, Relaxation, Zen... Smooth Riviera is a music program for live peacefully");
		station.setProperty("url", "http://listen.radionomy.com/smooth-riviera");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/20100406190156-smooth-riviera.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/smooth-riviera.m3u");
		station.setProperty("tag", 	"Chill-out EasyListening Classic Ambient");
		station.setProperty("mood", "anger");
		datastore.put(station);
		station = new Entity("Station");
		station.setProperty("name", "Bob Marley");
		station.setProperty("description", "Broadcast 24h/24 and 7/7, the radio offers more than 200 titles at present consist of original songs by Bob Marley but also Bob Family, remix, rework and on the blog full of information about the Lions.");
		station.setProperty("url", "http://listen.radionomy.com/bob-marley");
		station.setProperty("img", "http://i.radionomy.com/documents/radio/20110312221433-logo_bob.72x72.jpg");
		station.setProperty("m3u", "http://listen.radionomy.com/bob-marley.m3u");
		station.setProperty("tag", 	"Reggae RootsReggae Dub Ska Pop-Reggae");
		station.setProperty("mood", "neutral");
		datastore.put(station);
		
		
	}
}